spring:
  application:
    name: findex
  datasource:
    url: jdbc:postgresql://localhost:5432/findex
    username: findex
    password: findex1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# DB config
  config:
    import: "classpath:db.yaml"