spring:
  application:
    name: findex
  datasource:
    url: jdbc:postgresql://localhost:5432/findex
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # DB config
  config:
    import: "classpath:db.yaml"

# Open API
# 개발 환경: Run > Edit Configurations > Environment variables에 `OPEN_API_KEY=발급 받은 키`를 등록합니다.
# 운영 환경: OS 환경 변수 등록 또는 dotenv-spring-boot 외부 라이브러리를 고려합니다.
openapi:
  base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
  api-key: ${OPEN_API_KEY}