spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/findex
    username: findex
    password: findex1234

    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        #        use_sql_comments: true
        show_sql: true


# logging Config
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace